config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :documents do
    resources :documents_users, only: [:new, :create, :destroy, :index]
  end
  resources :operations, only: :create
  root "documents#index"
end

app/models/document.rb
class Document < ApplicationRecord
  include ContentBuilder

  belongs_to :creator, class_name: :User, foreign_key: :user_id
  has_many :operations
  has_many :documents_users, dependent: :destroy
  has_many :users, through: :documents_users

  attribute :revision, :integer, default: 1

  def editors
    documents_users.pluck(:user_id) << user_id
  end

  def users_to_add
    User.where.not(id: editors)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  load_and_authorize_resource

  def create
    @document = current_user.own_documents.create(title: "untitled", content: "")
    redirect_to document_path(@document.id)
  end
end

app/views/documents/index.html.erb
<% @documents.each do |document| %>
  <%= link_to document.title, document_path(document) %>
  <br/>
<% end %>
<%= link_to "create", documents_path, method: :post %>

app/views/documents/show.html.erb
<% if can? :update, DocumentsUser %>
  <%= link_to  "editors", document_documents_users_url(@document) %>
<% end%>
<%= form_with model: @document do |form| %>
  <%= form.text_field :title %></br>
  <%= form.text_area :content, id: "story",
                     data: {revision: @document.revision, id: @document.id, user_id: current_user.id} %>
<% end %>