config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :documents do
    resources :documents_users, only: [:new, :create, :destroy, :index]
  end
  resources :operations, only: :create
  root "documents#index"
end

app/models/documents_user.rb
class DocumentsUser < ApplicationRecord
    belongs_to :user
    belongs_to :document
end

app/controllers/documents_users_controller.rb
class DocumentsUsersController < ApplicationController 
  load_and_authorize_resource only: [:new, :create, :index]
  load_and_authorize_resource :document

  def create
    @documents_user.save!
    render :index
  end

  def destroy
    @user = User.find(params[:id]) 
    @document.users.delete(@user)
    render :index
  end

  def index
    @editors = @document.users
    @usersToAdd = User.where.not(id: @document.editors)
  end

  private

  def documents_user_params
    params[:documents_user][:document_id] = params[:document_id]
    params.require(:documents_user).permit(:user_id, :document_id)
  end
end

app/views/documents_users/_form.html.erb
<%= form_with model: @documents_user, url: document_documents_users_path(@document) do |f| %>
  <%= f.select :user_id, options_for_select(@document.users_to_add.pluck(:email, :id)) %>
  <%= f.submit "Submit", disable_with: 'Submiting...' %>
<% end %>

app/views/documents_users/index.html.erb
<% @document.users.each do |user| %>
  <%= user.email%>
  <%= link_to "destroy", document_documents_user_path(@document, user.id) , method: :delete %>
  <br/>
<% end %>
<%= link_to  "new editor", new_document_documents_user_url(@document) %>

app/views/documents_users/new.html.erb
<%= render partial: "documents_users/form" %>